///////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 3.6
//  \   \         Application : 7 Series FPGAs Transceivers Wizard
//  /   /         Filename : gtwizard_0.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\
//
//
// Module gtwizard_0 (a Core Top)
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`default_nettype wire

`timescale 1ns / 1ps
`define DLY #1

//***************************** Entity Declaration ****************************
(* DowngradeIPIdentifiedWarnings="yes" *)

(* X_CORE_INFO = "gtwizard_0,gtwizard_v3_6_10,{protocol_file=Start_from_scratch}" *) 
(* CORE_GENERATION_INFO = "gtwizard_0,gtwizard_v3_6_10,{protocol_file=Start_from_scratch}" *)module gtwizard_0 
(
input           sysclk_in,
input           soft_reset_tx_in,
input           soft_reset_rx_in,
input           dont_reset_on_data_error_in,
output          gt0_tx_fsm_reset_done_out,
output          gt0_rx_fsm_reset_done_out,
input           gt0_data_valid_in,
output          gt1_tx_fsm_reset_done_out,
output          gt1_rx_fsm_reset_done_out,
input           gt1_data_valid_in,
output          gt2_tx_fsm_reset_done_out,
output          gt2_rx_fsm_reset_done_out,
input           gt2_data_valid_in,
output          gt3_tx_fsm_reset_done_out,
output          gt3_rx_fsm_reset_done_out,
input           gt3_data_valid_in,
output          gt4_tx_fsm_reset_done_out,
output          gt4_rx_fsm_reset_done_out,
input           gt4_data_valid_in,
output          gt5_tx_fsm_reset_done_out,
output          gt5_rx_fsm_reset_done_out,
input           gt5_data_valid_in,
output          gt6_tx_fsm_reset_done_out,
output          gt6_rx_fsm_reset_done_out,
input           gt6_data_valid_in,

    //_________________________________________________________________________
    //GT0  (X1Y0)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          gt0_cpllfbclklost_out,
    output          gt0_cplllock_out,
    input           gt0_cplllockdetclk_in,
    input           gt0_cpllreset_in,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt0_gtrefclk0_in,
    input           gt0_gtrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt0_drpaddr_in,
    input           gt0_drpclk_in,
    input   [15:0]  gt0_drpdi_in,
    output  [15:0]  gt0_drpdo_out,
    input           gt0_drpen_in,
    output          gt0_drprdy_out,
    input           gt0_drpwe_in,
    //------------------------- Digital Monitor Ports --------------------------
    output  [7:0]   gt0_dmonitorout_out,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt0_eyescanreset_in,
    input           gt0_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt0_eyescandataerror_out,
    input           gt0_eyescantrigger_in,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt0_rxusrclk_in,
    input           gt0_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  gt0_rxdata_out,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           gt0_gtxrxp_in,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt0_gtxrxn_in,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt0_rxdfelpmreset_in,
    output  [6:0]   gt0_rxmonitorout_out,
    input   [1:0]   gt0_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt0_rxoutclk_out,
    output          gt0_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt0_gtrxreset_in,
    input           gt0_rxpmareset_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt0_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt0_gttxreset_in,
    input           gt0_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt0_txusrclk_in,
    input           gt0_txusrclk2_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  gt0_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt0_gtxtxn_out,
    output          gt0_gtxtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt0_txoutclk_out,
    output          gt0_txoutclkfabric_out,
    output          gt0_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt0_txresetdone_out,

    //GT1  (X1Y1)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          gt1_cpllfbclklost_out,
    output          gt1_cplllock_out,
    input           gt1_cplllockdetclk_in,
    input           gt1_cpllreset_in,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt1_gtrefclk0_in,
    input           gt1_gtrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt1_drpaddr_in,
    input           gt1_drpclk_in,
    input   [15:0]  gt1_drpdi_in,
    output  [15:0]  gt1_drpdo_out,
    input           gt1_drpen_in,
    output          gt1_drprdy_out,
    input           gt1_drpwe_in,
    //------------------------- Digital Monitor Ports --------------------------
    output  [7:0]   gt1_dmonitorout_out,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt1_eyescanreset_in,
    input           gt1_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt1_eyescandataerror_out,
    input           gt1_eyescantrigger_in,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt1_rxusrclk_in,
    input           gt1_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  gt1_rxdata_out,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           gt1_gtxrxp_in,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt1_gtxrxn_in,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt1_rxdfelpmreset_in,
    output  [6:0]   gt1_rxmonitorout_out,
    input   [1:0]   gt1_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt1_rxoutclk_out,
    output          gt1_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt1_gtrxreset_in,
    input           gt1_rxpmareset_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt1_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt1_gttxreset_in,
    input           gt1_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt1_txusrclk_in,
    input           gt1_txusrclk2_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  gt1_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt1_gtxtxn_out,
    output          gt1_gtxtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt1_txoutclk_out,
    output          gt1_txoutclkfabric_out,
    output          gt1_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt1_txresetdone_out,

    //GT2  (X1Y2)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          gt2_cpllfbclklost_out,
    output          gt2_cplllock_out,
    input           gt2_cplllockdetclk_in,
    input           gt2_cpllreset_in,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt2_gtrefclk0_in,
    input           gt2_gtrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt2_drpaddr_in,
    input           gt2_drpclk_in,
    input   [15:0]  gt2_drpdi_in,
    output  [15:0]  gt2_drpdo_out,
    input           gt2_drpen_in,
    output          gt2_drprdy_out,
    input           gt2_drpwe_in,
    //------------------------- Digital Monitor Ports --------------------------
    output  [7:0]   gt2_dmonitorout_out,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt2_eyescanreset_in,
    input           gt2_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt2_eyescandataerror_out,
    input           gt2_eyescantrigger_in,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt2_rxusrclk_in,
    input           gt2_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  gt2_rxdata_out,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           gt2_gtxrxp_in,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt2_gtxrxn_in,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt2_rxdfelpmreset_in,
    output  [6:0]   gt2_rxmonitorout_out,
    input   [1:0]   gt2_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt2_rxoutclk_out,
    output          gt2_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt2_gtrxreset_in,
    input           gt2_rxpmareset_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt2_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt2_gttxreset_in,
    input           gt2_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt2_txusrclk_in,
    input           gt2_txusrclk2_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  gt2_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt2_gtxtxn_out,
    output          gt2_gtxtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt2_txoutclk_out,
    output          gt2_txoutclkfabric_out,
    output          gt2_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt2_txresetdone_out,

    //GT3  (X1Y3)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          gt3_cpllfbclklost_out,
    output          gt3_cplllock_out,
    input           gt3_cplllockdetclk_in,
    input           gt3_cpllreset_in,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt3_gtrefclk0_in,
    input           gt3_gtrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt3_drpaddr_in,
    input           gt3_drpclk_in,
    input   [15:0]  gt3_drpdi_in,
    output  [15:0]  gt3_drpdo_out,
    input           gt3_drpen_in,
    output          gt3_drprdy_out,
    input           gt3_drpwe_in,
    //------------------------- Digital Monitor Ports --------------------------
    output  [7:0]   gt3_dmonitorout_out,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt3_eyescanreset_in,
    input           gt3_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt3_eyescandataerror_out,
    input           gt3_eyescantrigger_in,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt3_rxusrclk_in,
    input           gt3_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  gt3_rxdata_out,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           gt3_gtxrxp_in,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt3_gtxrxn_in,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt3_rxdfelpmreset_in,
    output  [6:0]   gt3_rxmonitorout_out,
    input   [1:0]   gt3_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt3_rxoutclk_out,
    output          gt3_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt3_gtrxreset_in,
    input           gt3_rxpmareset_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt3_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt3_gttxreset_in,
    input           gt3_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt3_txusrclk_in,
    input           gt3_txusrclk2_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  gt3_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt3_gtxtxn_out,
    output          gt3_gtxtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt3_txoutclk_out,
    output          gt3_txoutclkfabric_out,
    output          gt3_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt3_txresetdone_out,

    //GT4  (X1Y4)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          gt4_cpllfbclklost_out,
    output          gt4_cplllock_out,
    input           gt4_cplllockdetclk_in,
    input           gt4_cpllreset_in,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt4_gtrefclk0_in,
    input           gt4_gtrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt4_drpaddr_in,
    input           gt4_drpclk_in,
    input   [15:0]  gt4_drpdi_in,
    output  [15:0]  gt4_drpdo_out,
    input           gt4_drpen_in,
    output          gt4_drprdy_out,
    input           gt4_drpwe_in,
    //------------------------- Digital Monitor Ports --------------------------
    output  [7:0]   gt4_dmonitorout_out,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt4_eyescanreset_in,
    input           gt4_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt4_eyescandataerror_out,
    input           gt4_eyescantrigger_in,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt4_rxusrclk_in,
    input           gt4_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  gt4_rxdata_out,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           gt4_gtxrxp_in,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt4_gtxrxn_in,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt4_rxdfelpmreset_in,
    output  [6:0]   gt4_rxmonitorout_out,
    input   [1:0]   gt4_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt4_rxoutclk_out,
    output          gt4_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt4_gtrxreset_in,
    input           gt4_rxpmareset_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt4_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt4_gttxreset_in,
    input           gt4_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt4_txusrclk_in,
    input           gt4_txusrclk2_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  gt4_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt4_gtxtxn_out,
    output          gt4_gtxtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt4_txoutclk_out,
    output          gt4_txoutclkfabric_out,
    output          gt4_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt4_txresetdone_out,

    //GT5  (X1Y5)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          gt5_cpllfbclklost_out,
    output          gt5_cplllock_out,
    input           gt5_cplllockdetclk_in,
    input           gt5_cpllreset_in,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt5_gtrefclk0_in,
    input           gt5_gtrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt5_drpaddr_in,
    input           gt5_drpclk_in,
    input   [15:0]  gt5_drpdi_in,
    output  [15:0]  gt5_drpdo_out,
    input           gt5_drpen_in,
    output          gt5_drprdy_out,
    input           gt5_drpwe_in,
    //------------------------- Digital Monitor Ports --------------------------
    output  [7:0]   gt5_dmonitorout_out,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt5_eyescanreset_in,
    input           gt5_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt5_eyescandataerror_out,
    input           gt5_eyescantrigger_in,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt5_rxusrclk_in,
    input           gt5_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  gt5_rxdata_out,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           gt5_gtxrxp_in,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt5_gtxrxn_in,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt5_rxdfelpmreset_in,
    output  [6:0]   gt5_rxmonitorout_out,
    input   [1:0]   gt5_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt5_rxoutclk_out,
    output          gt5_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt5_gtrxreset_in,
    input           gt5_rxpmareset_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt5_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt5_gttxreset_in,
    input           gt5_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt5_txusrclk_in,
    input           gt5_txusrclk2_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  gt5_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt5_gtxtxn_out,
    output          gt5_gtxtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt5_txoutclk_out,
    output          gt5_txoutclkfabric_out,
    output          gt5_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt5_txresetdone_out,

    //GT6  (X1Y6)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
    output          gt6_cpllfbclklost_out,
    output          gt6_cplllock_out,
    input           gt6_cplllockdetclk_in,
    input           gt6_cpllreset_in,
    //------------------------ Channel - Clocking Ports ------------------------
    input           gt6_gtrefclk0_in,
    input           gt6_gtrefclk1_in,
    //-------------------------- Channel - DRP Ports  --------------------------
    input   [8:0]   gt6_drpaddr_in,
    input           gt6_drpclk_in,
    input   [15:0]  gt6_drpdi_in,
    output  [15:0]  gt6_drpdo_out,
    input           gt6_drpen_in,
    output          gt6_drprdy_out,
    input           gt6_drpwe_in,
    //------------------------- Digital Monitor Ports --------------------------
    output  [7:0]   gt6_dmonitorout_out,
    //------------------- RX Initialization and Reset Ports --------------------
    input           gt6_eyescanreset_in,
    input           gt6_rxuserrdy_in,
    //------------------------ RX Margin Analysis Ports ------------------------
    output          gt6_eyescandataerror_out,
    input           gt6_eyescantrigger_in,
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
    input           gt6_rxusrclk_in,
    input           gt6_rxusrclk2_in,
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
    output  [31:0]  gt6_rxdata_out,
    //------------------------- Receive Ports - RX AFE -------------------------
    input           gt6_gtxrxp_in,
    //---------------------- Receive Ports - RX AFE Ports ----------------------
    input           gt6_gtxrxn_in,
    //------------------- Receive Ports - RX Equalizer Ports -------------------
    input           gt6_rxdfelpmreset_in,
    output  [6:0]   gt6_rxmonitorout_out,
    input   [1:0]   gt6_rxmonitorsel_in,
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
    output          gt6_rxoutclk_out,
    output          gt6_rxoutclkfabric_out,
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
    input           gt6_gtrxreset_in,
    input           gt6_rxpmareset_in,
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
    output          gt6_rxresetdone_out,
    //------------------- TX Initialization and Reset Ports --------------------
    input           gt6_gttxreset_in,
    input           gt6_txuserrdy_in,
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
    input           gt6_txusrclk_in,
    input           gt6_txusrclk2_in,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [31:0]  gt6_txdata_in,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          gt6_gtxtxn_out,
    output          gt6_gtxtxp_out,
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
    output          gt6_txoutclk_out,
    output          gt6_txoutclkfabric_out,
    output          gt6_txoutclkpcs_out,
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
    output          gt6_txresetdone_out,


    //____________________________COMMON PORTS________________________________
    input      gt0_qplloutclk_in,
    input      gt0_qplloutrefclk_in,
    input      gt1_qplloutclk_in,
    input      gt1_qplloutrefclk_in

);

//-----------------------Init Wrapper Instatiation--------------------
    gtwizard_0_init #
    (
        .EXAMPLE_SIM_GTRESET_SPEEDUP    ("TRUE"),
        .EXAMPLE_SIMULATION             (0),
        .USE_BUFG                       (0),
        .STABLE_CLOCK_PERIOD            (10),
        .EXAMPLE_USE_CHIPSCOPE          (0)
    )
    inst
    (
     .sysclk_in(sysclk_in),
     .soft_reset_tx_in(soft_reset_tx_in),
     .soft_reset_rx_in(soft_reset_rx_in),
     .dont_reset_on_data_error_in(dont_reset_on_data_error_in),
     .gt0_tx_fsm_reset_done_out(gt0_tx_fsm_reset_done_out),
     .gt0_rx_fsm_reset_done_out(gt0_rx_fsm_reset_done_out),
     .gt0_data_valid_in(gt0_data_valid_in),
     .gt1_tx_fsm_reset_done_out(gt1_tx_fsm_reset_done_out),
     .gt1_rx_fsm_reset_done_out(gt1_rx_fsm_reset_done_out),
     .gt1_data_valid_in(gt1_data_valid_in),
     .gt2_tx_fsm_reset_done_out(gt2_tx_fsm_reset_done_out),
     .gt2_rx_fsm_reset_done_out(gt2_rx_fsm_reset_done_out),
     .gt2_data_valid_in(gt2_data_valid_in),
     .gt3_tx_fsm_reset_done_out(gt3_tx_fsm_reset_done_out),
     .gt3_rx_fsm_reset_done_out(gt3_rx_fsm_reset_done_out),
     .gt3_data_valid_in(gt3_data_valid_in),
     .gt4_tx_fsm_reset_done_out(gt4_tx_fsm_reset_done_out),
     .gt4_rx_fsm_reset_done_out(gt4_rx_fsm_reset_done_out),
     .gt4_data_valid_in(gt4_data_valid_in),
     .gt5_tx_fsm_reset_done_out(gt5_tx_fsm_reset_done_out),
     .gt5_rx_fsm_reset_done_out(gt5_rx_fsm_reset_done_out),
     .gt5_data_valid_in(gt5_data_valid_in),
     .gt6_tx_fsm_reset_done_out(gt6_tx_fsm_reset_done_out),
     .gt6_rx_fsm_reset_done_out(gt6_rx_fsm_reset_done_out),
     .gt6_data_valid_in(gt6_data_valid_in),

    //_________________________________________________________________________
    //GT0  (X1Y0)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
        .gt0_cpllfbclklost_out          (gt0_cpllfbclklost_out), // output wire gt0_cpllfbclklost_out
        .gt0_cplllock_out               (gt0_cplllock_out), // output wire gt0_cplllock_out
        .gt0_cplllockdetclk_in          (gt0_cplllockdetclk_in), // input wire gt0_cplllockdetclk_in
        .gt0_cpllreset_in               (gt0_cpllreset_in), // input wire gt0_cpllreset_in
    //------------------------ Channel - Clocking Ports ------------------------
        .gt0_gtrefclk0_in               (gt0_gtrefclk0_in), // input wire gt0_gtrefclk0_in
        .gt0_gtrefclk1_in               (gt0_gtrefclk1_in), // input wire gt0_gtrefclk1_in
    //-------------------------- Channel - DRP Ports  --------------------------
        .gt0_drpaddr_in                 (gt0_drpaddr_in), // input wire [8:0] gt0_drpaddr_in
        .gt0_drpclk_in                  (gt0_drpclk_in), // input wire gt0_drpclk_in
        .gt0_drpdi_in                   (gt0_drpdi_in), // input wire [15:0] gt0_drpdi_in
        .gt0_drpdo_out                  (gt0_drpdo_out), // output wire [15:0] gt0_drpdo_out
        .gt0_drpen_in                   (gt0_drpen_in), // input wire gt0_drpen_in
        .gt0_drprdy_out                 (gt0_drprdy_out), // output wire gt0_drprdy_out
        .gt0_drpwe_in                   (gt0_drpwe_in), // input wire gt0_drpwe_in
    //------------------------- Digital Monitor Ports --------------------------
        .gt0_dmonitorout_out            (gt0_dmonitorout_out), // output wire [7:0] gt0_dmonitorout_out
    //------------------- RX Initialization and Reset Ports --------------------
        .gt0_eyescanreset_in            (gt0_eyescanreset_in), // input wire gt0_eyescanreset_in
        .gt0_rxuserrdy_in               (gt0_rxuserrdy_in), // input wire gt0_rxuserrdy_in
    //------------------------ RX Margin Analysis Ports ------------------------
        .gt0_eyescandataerror_out       (gt0_eyescandataerror_out), // output wire gt0_eyescandataerror_out
        .gt0_eyescantrigger_in          (gt0_eyescantrigger_in), // input wire gt0_eyescantrigger_in
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt0_rxusrclk_in                (gt0_rxusrclk_in), // input wire gt0_rxusrclk_in
        .gt0_rxusrclk2_in               (gt0_rxusrclk2_in), // input wire gt0_rxusrclk2_in
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt0_rxdata_out                 (gt0_rxdata_out), // output wire [31:0] gt0_rxdata_out
    //------------------------- Receive Ports - RX AFE -------------------------
        .gt0_gtxrxp_in                  (gt0_gtxrxp_in), // input wire gt0_gtxrxp_in
    //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt0_gtxrxn_in                  (gt0_gtxrxn_in), // input wire gt0_gtxrxn_in
    //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt0_rxdfelpmreset_in           (gt0_rxdfelpmreset_in), // input wire gt0_rxdfelpmreset_in
        .gt0_rxmonitorout_out           (gt0_rxmonitorout_out), // output wire [6:0] gt0_rxmonitorout_out
        .gt0_rxmonitorsel_in            (gt0_rxmonitorsel_in), // input wire [1:0] gt0_rxmonitorsel_in
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .gt0_rxoutclk_out               (gt0_rxoutclk_out), // output wire gt0_rxoutclk_out
        .gt0_rxoutclkfabric_out         (gt0_rxoutclkfabric_out), // output wire gt0_rxoutclkfabric_out
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt0_gtrxreset_in               (gt0_gtrxreset_in), // input wire gt0_gtrxreset_in
        .gt0_rxpmareset_in              (gt0_rxpmareset_in), // input wire gt0_rxpmareset_in
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt0_rxresetdone_out            (gt0_rxresetdone_out), // output wire gt0_rxresetdone_out
    //------------------- TX Initialization and Reset Ports --------------------
        .gt0_gttxreset_in               (gt0_gttxreset_in), // input wire gt0_gttxreset_in
        .gt0_txuserrdy_in               (gt0_txuserrdy_in), // input wire gt0_txuserrdy_in
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt0_txusrclk_in                (gt0_txusrclk_in), // input wire gt0_txusrclk_in
        .gt0_txusrclk2_in               (gt0_txusrclk2_in), // input wire gt0_txusrclk2_in
    //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt0_txdata_in                  (gt0_txdata_in), // input wire [31:0] gt0_txdata_in
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt0_gtxtxn_out                 (gt0_gtxtxn_out), // output wire gt0_gtxtxn_out
        .gt0_gtxtxp_out                 (gt0_gtxtxp_out), // output wire gt0_gtxtxp_out
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt0_txoutclk_out               (gt0_txoutclk_out), // output wire gt0_txoutclk_out
        .gt0_txoutclkfabric_out         (gt0_txoutclkfabric_out), // output wire gt0_txoutclkfabric_out
        .gt0_txoutclkpcs_out            (gt0_txoutclkpcs_out), // output wire gt0_txoutclkpcs_out
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt0_txresetdone_out            (gt0_txresetdone_out), // output wire gt0_txresetdone_out

    //GT1  (X1Y1)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
        .gt1_cpllfbclklost_out          (gt1_cpllfbclklost_out), // output wire gt1_cpllfbclklost_out
        .gt1_cplllock_out               (gt1_cplllock_out), // output wire gt1_cplllock_out
        .gt1_cplllockdetclk_in          (gt1_cplllockdetclk_in), // input wire gt1_cplllockdetclk_in
        .gt1_cpllreset_in               (gt1_cpllreset_in), // input wire gt1_cpllreset_in
    //------------------------ Channel - Clocking Ports ------------------------
        .gt1_gtrefclk0_in               (gt1_gtrefclk0_in), // input wire gt1_gtrefclk0_in
        .gt1_gtrefclk1_in               (gt1_gtrefclk1_in), // input wire gt1_gtrefclk1_in
    //-------------------------- Channel - DRP Ports  --------------------------
        .gt1_drpaddr_in                 (gt1_drpaddr_in), // input wire [8:0] gt1_drpaddr_in
        .gt1_drpclk_in                  (gt1_drpclk_in), // input wire gt1_drpclk_in
        .gt1_drpdi_in                   (gt1_drpdi_in), // input wire [15:0] gt1_drpdi_in
        .gt1_drpdo_out                  (gt1_drpdo_out), // output wire [15:0] gt1_drpdo_out
        .gt1_drpen_in                   (gt1_drpen_in), // input wire gt1_drpen_in
        .gt1_drprdy_out                 (gt1_drprdy_out), // output wire gt1_drprdy_out
        .gt1_drpwe_in                   (gt1_drpwe_in), // input wire gt1_drpwe_in
    //------------------------- Digital Monitor Ports --------------------------
        .gt1_dmonitorout_out            (gt1_dmonitorout_out), // output wire [7:0] gt1_dmonitorout_out
    //------------------- RX Initialization and Reset Ports --------------------
        .gt1_eyescanreset_in            (gt1_eyescanreset_in), // input wire gt1_eyescanreset_in
        .gt1_rxuserrdy_in               (gt1_rxuserrdy_in), // input wire gt1_rxuserrdy_in
    //------------------------ RX Margin Analysis Ports ------------------------
        .gt1_eyescandataerror_out       (gt1_eyescandataerror_out), // output wire gt1_eyescandataerror_out
        .gt1_eyescantrigger_in          (gt1_eyescantrigger_in), // input wire gt1_eyescantrigger_in
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt1_rxusrclk_in                (gt1_rxusrclk_in), // input wire gt1_rxusrclk_in
        .gt1_rxusrclk2_in               (gt1_rxusrclk2_in), // input wire gt1_rxusrclk2_in
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt1_rxdata_out                 (gt1_rxdata_out), // output wire [31:0] gt1_rxdata_out
    //------------------------- Receive Ports - RX AFE -------------------------
        .gt1_gtxrxp_in                  (gt1_gtxrxp_in), // input wire gt1_gtxrxp_in
    //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt1_gtxrxn_in                  (gt1_gtxrxn_in), // input wire gt1_gtxrxn_in
    //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt1_rxdfelpmreset_in           (gt1_rxdfelpmreset_in), // input wire gt1_rxdfelpmreset_in
        .gt1_rxmonitorout_out           (gt1_rxmonitorout_out), // output wire [6:0] gt1_rxmonitorout_out
        .gt1_rxmonitorsel_in            (gt1_rxmonitorsel_in), // input wire [1:0] gt1_rxmonitorsel_in
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .gt1_rxoutclk_out               (gt1_rxoutclk_out), // output wire gt1_rxoutclk_out
        .gt1_rxoutclkfabric_out         (gt1_rxoutclkfabric_out), // output wire gt1_rxoutclkfabric_out
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt1_gtrxreset_in               (gt1_gtrxreset_in), // input wire gt1_gtrxreset_in
        .gt1_rxpmareset_in              (gt1_rxpmareset_in), // input wire gt1_rxpmareset_in
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt1_rxresetdone_out            (gt1_rxresetdone_out), // output wire gt1_rxresetdone_out
    //------------------- TX Initialization and Reset Ports --------------------
        .gt1_gttxreset_in               (gt1_gttxreset_in), // input wire gt1_gttxreset_in
        .gt1_txuserrdy_in               (gt1_txuserrdy_in), // input wire gt1_txuserrdy_in
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt1_txusrclk_in                (gt1_txusrclk_in), // input wire gt1_txusrclk_in
        .gt1_txusrclk2_in               (gt1_txusrclk2_in), // input wire gt1_txusrclk2_in
    //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt1_txdata_in                  (gt1_txdata_in), // input wire [31:0] gt1_txdata_in
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt1_gtxtxn_out                 (gt1_gtxtxn_out), // output wire gt1_gtxtxn_out
        .gt1_gtxtxp_out                 (gt1_gtxtxp_out), // output wire gt1_gtxtxp_out
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt1_txoutclk_out               (gt1_txoutclk_out), // output wire gt1_txoutclk_out
        .gt1_txoutclkfabric_out         (gt1_txoutclkfabric_out), // output wire gt1_txoutclkfabric_out
        .gt1_txoutclkpcs_out            (gt1_txoutclkpcs_out), // output wire gt1_txoutclkpcs_out
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt1_txresetdone_out            (gt1_txresetdone_out), // output wire gt1_txresetdone_out

    //GT2  (X1Y2)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
        .gt2_cpllfbclklost_out          (gt2_cpllfbclklost_out), // output wire gt2_cpllfbclklost_out
        .gt2_cplllock_out               (gt2_cplllock_out), // output wire gt2_cplllock_out
        .gt2_cplllockdetclk_in          (gt2_cplllockdetclk_in), // input wire gt2_cplllockdetclk_in
        .gt2_cpllreset_in               (gt2_cpllreset_in), // input wire gt2_cpllreset_in
    //------------------------ Channel - Clocking Ports ------------------------
        .gt2_gtrefclk0_in               (gt2_gtrefclk0_in), // input wire gt2_gtrefclk0_in
        .gt2_gtrefclk1_in               (gt2_gtrefclk1_in), // input wire gt2_gtrefclk1_in
    //-------------------------- Channel - DRP Ports  --------------------------
        .gt2_drpaddr_in                 (gt2_drpaddr_in), // input wire [8:0] gt2_drpaddr_in
        .gt2_drpclk_in                  (gt2_drpclk_in), // input wire gt2_drpclk_in
        .gt2_drpdi_in                   (gt2_drpdi_in), // input wire [15:0] gt2_drpdi_in
        .gt2_drpdo_out                  (gt2_drpdo_out), // output wire [15:0] gt2_drpdo_out
        .gt2_drpen_in                   (gt2_drpen_in), // input wire gt2_drpen_in
        .gt2_drprdy_out                 (gt2_drprdy_out), // output wire gt2_drprdy_out
        .gt2_drpwe_in                   (gt2_drpwe_in), // input wire gt2_drpwe_in
    //------------------------- Digital Monitor Ports --------------------------
        .gt2_dmonitorout_out            (gt2_dmonitorout_out), // output wire [7:0] gt2_dmonitorout_out
    //------------------- RX Initialization and Reset Ports --------------------
        .gt2_eyescanreset_in            (gt2_eyescanreset_in), // input wire gt2_eyescanreset_in
        .gt2_rxuserrdy_in               (gt2_rxuserrdy_in), // input wire gt2_rxuserrdy_in
    //------------------------ RX Margin Analysis Ports ------------------------
        .gt2_eyescandataerror_out       (gt2_eyescandataerror_out), // output wire gt2_eyescandataerror_out
        .gt2_eyescantrigger_in          (gt2_eyescantrigger_in), // input wire gt2_eyescantrigger_in
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt2_rxusrclk_in                (gt2_rxusrclk_in), // input wire gt2_rxusrclk_in
        .gt2_rxusrclk2_in               (gt2_rxusrclk2_in), // input wire gt2_rxusrclk2_in
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt2_rxdata_out                 (gt2_rxdata_out), // output wire [31:0] gt2_rxdata_out
    //------------------------- Receive Ports - RX AFE -------------------------
        .gt2_gtxrxp_in                  (gt2_gtxrxp_in), // input wire gt2_gtxrxp_in
    //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt2_gtxrxn_in                  (gt2_gtxrxn_in), // input wire gt2_gtxrxn_in
    //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt2_rxdfelpmreset_in           (gt2_rxdfelpmreset_in), // input wire gt2_rxdfelpmreset_in
        .gt2_rxmonitorout_out           (gt2_rxmonitorout_out), // output wire [6:0] gt2_rxmonitorout_out
        .gt2_rxmonitorsel_in            (gt2_rxmonitorsel_in), // input wire [1:0] gt2_rxmonitorsel_in
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .gt2_rxoutclk_out               (gt2_rxoutclk_out), // output wire gt2_rxoutclk_out
        .gt2_rxoutclkfabric_out         (gt2_rxoutclkfabric_out), // output wire gt2_rxoutclkfabric_out
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt2_gtrxreset_in               (gt2_gtrxreset_in), // input wire gt2_gtrxreset_in
        .gt2_rxpmareset_in              (gt2_rxpmareset_in), // input wire gt2_rxpmareset_in
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt2_rxresetdone_out            (gt2_rxresetdone_out), // output wire gt2_rxresetdone_out
    //------------------- TX Initialization and Reset Ports --------------------
        .gt2_gttxreset_in               (gt2_gttxreset_in), // input wire gt2_gttxreset_in
        .gt2_txuserrdy_in               (gt2_txuserrdy_in), // input wire gt2_txuserrdy_in
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt2_txusrclk_in                (gt2_txusrclk_in), // input wire gt2_txusrclk_in
        .gt2_txusrclk2_in               (gt2_txusrclk2_in), // input wire gt2_txusrclk2_in
    //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt2_txdata_in                  (gt2_txdata_in), // input wire [31:0] gt2_txdata_in
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt2_gtxtxn_out                 (gt2_gtxtxn_out), // output wire gt2_gtxtxn_out
        .gt2_gtxtxp_out                 (gt2_gtxtxp_out), // output wire gt2_gtxtxp_out
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt2_txoutclk_out               (gt2_txoutclk_out), // output wire gt2_txoutclk_out
        .gt2_txoutclkfabric_out         (gt2_txoutclkfabric_out), // output wire gt2_txoutclkfabric_out
        .gt2_txoutclkpcs_out            (gt2_txoutclkpcs_out), // output wire gt2_txoutclkpcs_out
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt2_txresetdone_out            (gt2_txresetdone_out), // output wire gt2_txresetdone_out

    //GT3  (X1Y3)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
        .gt3_cpllfbclklost_out          (gt3_cpllfbclklost_out), // output wire gt3_cpllfbclklost_out
        .gt3_cplllock_out               (gt3_cplllock_out), // output wire gt3_cplllock_out
        .gt3_cplllockdetclk_in          (gt3_cplllockdetclk_in), // input wire gt3_cplllockdetclk_in
        .gt3_cpllreset_in               (gt3_cpllreset_in), // input wire gt3_cpllreset_in
    //------------------------ Channel - Clocking Ports ------------------------
        .gt3_gtrefclk0_in               (gt3_gtrefclk0_in), // input wire gt3_gtrefclk0_in
        .gt3_gtrefclk1_in               (gt3_gtrefclk1_in), // input wire gt3_gtrefclk1_in
    //-------------------------- Channel - DRP Ports  --------------------------
        .gt3_drpaddr_in                 (gt3_drpaddr_in), // input wire [8:0] gt3_drpaddr_in
        .gt3_drpclk_in                  (gt3_drpclk_in), // input wire gt3_drpclk_in
        .gt3_drpdi_in                   (gt3_drpdi_in), // input wire [15:0] gt3_drpdi_in
        .gt3_drpdo_out                  (gt3_drpdo_out), // output wire [15:0] gt3_drpdo_out
        .gt3_drpen_in                   (gt3_drpen_in), // input wire gt3_drpen_in
        .gt3_drprdy_out                 (gt3_drprdy_out), // output wire gt3_drprdy_out
        .gt3_drpwe_in                   (gt3_drpwe_in), // input wire gt3_drpwe_in
    //------------------------- Digital Monitor Ports --------------------------
        .gt3_dmonitorout_out            (gt3_dmonitorout_out), // output wire [7:0] gt3_dmonitorout_out
    //------------------- RX Initialization and Reset Ports --------------------
        .gt3_eyescanreset_in            (gt3_eyescanreset_in), // input wire gt3_eyescanreset_in
        .gt3_rxuserrdy_in               (gt3_rxuserrdy_in), // input wire gt3_rxuserrdy_in
    //------------------------ RX Margin Analysis Ports ------------------------
        .gt3_eyescandataerror_out       (gt3_eyescandataerror_out), // output wire gt3_eyescandataerror_out
        .gt3_eyescantrigger_in          (gt3_eyescantrigger_in), // input wire gt3_eyescantrigger_in
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt3_rxusrclk_in                (gt3_rxusrclk_in), // input wire gt3_rxusrclk_in
        .gt3_rxusrclk2_in               (gt3_rxusrclk2_in), // input wire gt3_rxusrclk2_in
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt3_rxdata_out                 (gt3_rxdata_out), // output wire [31:0] gt3_rxdata_out
    //------------------------- Receive Ports - RX AFE -------------------------
        .gt3_gtxrxp_in                  (gt3_gtxrxp_in), // input wire gt3_gtxrxp_in
    //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt3_gtxrxn_in                  (gt3_gtxrxn_in), // input wire gt3_gtxrxn_in
    //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt3_rxdfelpmreset_in           (gt3_rxdfelpmreset_in), // input wire gt3_rxdfelpmreset_in
        .gt3_rxmonitorout_out           (gt3_rxmonitorout_out), // output wire [6:0] gt3_rxmonitorout_out
        .gt3_rxmonitorsel_in            (gt3_rxmonitorsel_in), // input wire [1:0] gt3_rxmonitorsel_in
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .gt3_rxoutclk_out               (gt3_rxoutclk_out), // output wire gt3_rxoutclk_out
        .gt3_rxoutclkfabric_out         (gt3_rxoutclkfabric_out), // output wire gt3_rxoutclkfabric_out
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt3_gtrxreset_in               (gt3_gtrxreset_in), // input wire gt3_gtrxreset_in
        .gt3_rxpmareset_in              (gt3_rxpmareset_in), // input wire gt3_rxpmareset_in
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt3_rxresetdone_out            (gt3_rxresetdone_out), // output wire gt3_rxresetdone_out
    //------------------- TX Initialization and Reset Ports --------------------
        .gt3_gttxreset_in               (gt3_gttxreset_in), // input wire gt3_gttxreset_in
        .gt3_txuserrdy_in               (gt3_txuserrdy_in), // input wire gt3_txuserrdy_in
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt3_txusrclk_in                (gt3_txusrclk_in), // input wire gt3_txusrclk_in
        .gt3_txusrclk2_in               (gt3_txusrclk2_in), // input wire gt3_txusrclk2_in
    //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt3_txdata_in                  (gt3_txdata_in), // input wire [31:0] gt3_txdata_in
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt3_gtxtxn_out                 (gt3_gtxtxn_out), // output wire gt3_gtxtxn_out
        .gt3_gtxtxp_out                 (gt3_gtxtxp_out), // output wire gt3_gtxtxp_out
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt3_txoutclk_out               (gt3_txoutclk_out), // output wire gt3_txoutclk_out
        .gt3_txoutclkfabric_out         (gt3_txoutclkfabric_out), // output wire gt3_txoutclkfabric_out
        .gt3_txoutclkpcs_out            (gt3_txoutclkpcs_out), // output wire gt3_txoutclkpcs_out
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt3_txresetdone_out            (gt3_txresetdone_out), // output wire gt3_txresetdone_out

    //GT4  (X1Y4)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
        .gt4_cpllfbclklost_out          (gt4_cpllfbclklost_out), // output wire gt4_cpllfbclklost_out
        .gt4_cplllock_out               (gt4_cplllock_out), // output wire gt4_cplllock_out
        .gt4_cplllockdetclk_in          (gt4_cplllockdetclk_in), // input wire gt4_cplllockdetclk_in
        .gt4_cpllreset_in               (gt4_cpllreset_in), // input wire gt4_cpllreset_in
    //------------------------ Channel - Clocking Ports ------------------------
        .gt4_gtrefclk0_in               (gt4_gtrefclk0_in), // input wire gt4_gtrefclk0_in
        .gt4_gtrefclk1_in               (gt4_gtrefclk1_in), // input wire gt4_gtrefclk1_in
    //-------------------------- Channel - DRP Ports  --------------------------
        .gt4_drpaddr_in                 (gt4_drpaddr_in), // input wire [8:0] gt4_drpaddr_in
        .gt4_drpclk_in                  (gt4_drpclk_in), // input wire gt4_drpclk_in
        .gt4_drpdi_in                   (gt4_drpdi_in), // input wire [15:0] gt4_drpdi_in
        .gt4_drpdo_out                  (gt4_drpdo_out), // output wire [15:0] gt4_drpdo_out
        .gt4_drpen_in                   (gt4_drpen_in), // input wire gt4_drpen_in
        .gt4_drprdy_out                 (gt4_drprdy_out), // output wire gt4_drprdy_out
        .gt4_drpwe_in                   (gt4_drpwe_in), // input wire gt4_drpwe_in
    //------------------------- Digital Monitor Ports --------------------------
        .gt4_dmonitorout_out            (gt4_dmonitorout_out), // output wire [7:0] gt4_dmonitorout_out
    //------------------- RX Initialization and Reset Ports --------------------
        .gt4_eyescanreset_in            (gt4_eyescanreset_in), // input wire gt4_eyescanreset_in
        .gt4_rxuserrdy_in               (gt4_rxuserrdy_in), // input wire gt4_rxuserrdy_in
    //------------------------ RX Margin Analysis Ports ------------------------
        .gt4_eyescandataerror_out       (gt4_eyescandataerror_out), // output wire gt4_eyescandataerror_out
        .gt4_eyescantrigger_in          (gt4_eyescantrigger_in), // input wire gt4_eyescantrigger_in
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt4_rxusrclk_in                (gt4_rxusrclk_in), // input wire gt4_rxusrclk_in
        .gt4_rxusrclk2_in               (gt4_rxusrclk2_in), // input wire gt4_rxusrclk2_in
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt4_rxdata_out                 (gt4_rxdata_out), // output wire [31:0] gt4_rxdata_out
    //------------------------- Receive Ports - RX AFE -------------------------
        .gt4_gtxrxp_in                  (gt4_gtxrxp_in), // input wire gt4_gtxrxp_in
    //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt4_gtxrxn_in                  (gt4_gtxrxn_in), // input wire gt4_gtxrxn_in
    //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt4_rxdfelpmreset_in           (gt4_rxdfelpmreset_in), // input wire gt4_rxdfelpmreset_in
        .gt4_rxmonitorout_out           (gt4_rxmonitorout_out), // output wire [6:0] gt4_rxmonitorout_out
        .gt4_rxmonitorsel_in            (gt4_rxmonitorsel_in), // input wire [1:0] gt4_rxmonitorsel_in
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .gt4_rxoutclk_out               (gt4_rxoutclk_out), // output wire gt4_rxoutclk_out
        .gt4_rxoutclkfabric_out         (gt4_rxoutclkfabric_out), // output wire gt4_rxoutclkfabric_out
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt4_gtrxreset_in               (gt4_gtrxreset_in), // input wire gt4_gtrxreset_in
        .gt4_rxpmareset_in              (gt4_rxpmareset_in), // input wire gt4_rxpmareset_in
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt4_rxresetdone_out            (gt4_rxresetdone_out), // output wire gt4_rxresetdone_out
    //------------------- TX Initialization and Reset Ports --------------------
        .gt4_gttxreset_in               (gt4_gttxreset_in), // input wire gt4_gttxreset_in
        .gt4_txuserrdy_in               (gt4_txuserrdy_in), // input wire gt4_txuserrdy_in
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt4_txusrclk_in                (gt4_txusrclk_in), // input wire gt4_txusrclk_in
        .gt4_txusrclk2_in               (gt4_txusrclk2_in), // input wire gt4_txusrclk2_in
    //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt4_txdata_in                  (gt4_txdata_in), // input wire [31:0] gt4_txdata_in
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt4_gtxtxn_out                 (gt4_gtxtxn_out), // output wire gt4_gtxtxn_out
        .gt4_gtxtxp_out                 (gt4_gtxtxp_out), // output wire gt4_gtxtxp_out
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt4_txoutclk_out               (gt4_txoutclk_out), // output wire gt4_txoutclk_out
        .gt4_txoutclkfabric_out         (gt4_txoutclkfabric_out), // output wire gt4_txoutclkfabric_out
        .gt4_txoutclkpcs_out            (gt4_txoutclkpcs_out), // output wire gt4_txoutclkpcs_out
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt4_txresetdone_out            (gt4_txresetdone_out), // output wire gt4_txresetdone_out

    //GT5  (X1Y5)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
        .gt5_cpllfbclklost_out          (gt5_cpllfbclklost_out), // output wire gt5_cpllfbclklost_out
        .gt5_cplllock_out               (gt5_cplllock_out), // output wire gt5_cplllock_out
        .gt5_cplllockdetclk_in          (gt5_cplllockdetclk_in), // input wire gt5_cplllockdetclk_in
        .gt5_cpllreset_in               (gt5_cpllreset_in), // input wire gt5_cpllreset_in
    //------------------------ Channel - Clocking Ports ------------------------
        .gt5_gtrefclk0_in               (gt5_gtrefclk0_in), // input wire gt5_gtrefclk0_in
        .gt5_gtrefclk1_in               (gt5_gtrefclk1_in), // input wire gt5_gtrefclk1_in
    //-------------------------- Channel - DRP Ports  --------------------------
        .gt5_drpaddr_in                 (gt5_drpaddr_in), // input wire [8:0] gt5_drpaddr_in
        .gt5_drpclk_in                  (gt5_drpclk_in), // input wire gt5_drpclk_in
        .gt5_drpdi_in                   (gt5_drpdi_in), // input wire [15:0] gt5_drpdi_in
        .gt5_drpdo_out                  (gt5_drpdo_out), // output wire [15:0] gt5_drpdo_out
        .gt5_drpen_in                   (gt5_drpen_in), // input wire gt5_drpen_in
        .gt5_drprdy_out                 (gt5_drprdy_out), // output wire gt5_drprdy_out
        .gt5_drpwe_in                   (gt5_drpwe_in), // input wire gt5_drpwe_in
    //------------------------- Digital Monitor Ports --------------------------
        .gt5_dmonitorout_out            (gt5_dmonitorout_out), // output wire [7:0] gt5_dmonitorout_out
    //------------------- RX Initialization and Reset Ports --------------------
        .gt5_eyescanreset_in            (gt5_eyescanreset_in), // input wire gt5_eyescanreset_in
        .gt5_rxuserrdy_in               (gt5_rxuserrdy_in), // input wire gt5_rxuserrdy_in
    //------------------------ RX Margin Analysis Ports ------------------------
        .gt5_eyescandataerror_out       (gt5_eyescandataerror_out), // output wire gt5_eyescandataerror_out
        .gt5_eyescantrigger_in          (gt5_eyescantrigger_in), // input wire gt5_eyescantrigger_in
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt5_rxusrclk_in                (gt5_rxusrclk_in), // input wire gt5_rxusrclk_in
        .gt5_rxusrclk2_in               (gt5_rxusrclk2_in), // input wire gt5_rxusrclk2_in
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt5_rxdata_out                 (gt5_rxdata_out), // output wire [31:0] gt5_rxdata_out
    //------------------------- Receive Ports - RX AFE -------------------------
        .gt5_gtxrxp_in                  (gt5_gtxrxp_in), // input wire gt5_gtxrxp_in
    //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt5_gtxrxn_in                  (gt5_gtxrxn_in), // input wire gt5_gtxrxn_in
    //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt5_rxdfelpmreset_in           (gt5_rxdfelpmreset_in), // input wire gt5_rxdfelpmreset_in
        .gt5_rxmonitorout_out           (gt5_rxmonitorout_out), // output wire [6:0] gt5_rxmonitorout_out
        .gt5_rxmonitorsel_in            (gt5_rxmonitorsel_in), // input wire [1:0] gt5_rxmonitorsel_in
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .gt5_rxoutclk_out               (gt5_rxoutclk_out), // output wire gt5_rxoutclk_out
        .gt5_rxoutclkfabric_out         (gt5_rxoutclkfabric_out), // output wire gt5_rxoutclkfabric_out
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt5_gtrxreset_in               (gt5_gtrxreset_in), // input wire gt5_gtrxreset_in
        .gt5_rxpmareset_in              (gt5_rxpmareset_in), // input wire gt5_rxpmareset_in
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt5_rxresetdone_out            (gt5_rxresetdone_out), // output wire gt5_rxresetdone_out
    //------------------- TX Initialization and Reset Ports --------------------
        .gt5_gttxreset_in               (gt5_gttxreset_in), // input wire gt5_gttxreset_in
        .gt5_txuserrdy_in               (gt5_txuserrdy_in), // input wire gt5_txuserrdy_in
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt5_txusrclk_in                (gt5_txusrclk_in), // input wire gt5_txusrclk_in
        .gt5_txusrclk2_in               (gt5_txusrclk2_in), // input wire gt5_txusrclk2_in
    //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt5_txdata_in                  (gt5_txdata_in), // input wire [31:0] gt5_txdata_in
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt5_gtxtxn_out                 (gt5_gtxtxn_out), // output wire gt5_gtxtxn_out
        .gt5_gtxtxp_out                 (gt5_gtxtxp_out), // output wire gt5_gtxtxp_out
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt5_txoutclk_out               (gt5_txoutclk_out), // output wire gt5_txoutclk_out
        .gt5_txoutclkfabric_out         (gt5_txoutclkfabric_out), // output wire gt5_txoutclkfabric_out
        .gt5_txoutclkpcs_out            (gt5_txoutclkpcs_out), // output wire gt5_txoutclkpcs_out
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt5_txresetdone_out            (gt5_txresetdone_out), // output wire gt5_txresetdone_out

    //GT6  (X1Y6)
    //____________________________CHANNEL PORTS________________________________
    //------------------------------- CPLL Ports -------------------------------
        .gt6_cpllfbclklost_out          (gt6_cpllfbclklost_out), // output wire gt6_cpllfbclklost_out
        .gt6_cplllock_out               (gt6_cplllock_out), // output wire gt6_cplllock_out
        .gt6_cplllockdetclk_in          (gt6_cplllockdetclk_in), // input wire gt6_cplllockdetclk_in
        .gt6_cpllreset_in               (gt6_cpllreset_in), // input wire gt6_cpllreset_in
    //------------------------ Channel - Clocking Ports ------------------------
        .gt6_gtrefclk0_in               (gt6_gtrefclk0_in), // input wire gt6_gtrefclk0_in
        .gt6_gtrefclk1_in               (gt6_gtrefclk1_in), // input wire gt6_gtrefclk1_in
    //-------------------------- Channel - DRP Ports  --------------------------
        .gt6_drpaddr_in                 (gt6_drpaddr_in), // input wire [8:0] gt6_drpaddr_in
        .gt6_drpclk_in                  (gt6_drpclk_in), // input wire gt6_drpclk_in
        .gt6_drpdi_in                   (gt6_drpdi_in), // input wire [15:0] gt6_drpdi_in
        .gt6_drpdo_out                  (gt6_drpdo_out), // output wire [15:0] gt6_drpdo_out
        .gt6_drpen_in                   (gt6_drpen_in), // input wire gt6_drpen_in
        .gt6_drprdy_out                 (gt6_drprdy_out), // output wire gt6_drprdy_out
        .gt6_drpwe_in                   (gt6_drpwe_in), // input wire gt6_drpwe_in
    //------------------------- Digital Monitor Ports --------------------------
        .gt6_dmonitorout_out            (gt6_dmonitorout_out), // output wire [7:0] gt6_dmonitorout_out
    //------------------- RX Initialization and Reset Ports --------------------
        .gt6_eyescanreset_in            (gt6_eyescanreset_in), // input wire gt6_eyescanreset_in
        .gt6_rxuserrdy_in               (gt6_rxuserrdy_in), // input wire gt6_rxuserrdy_in
    //------------------------ RX Margin Analysis Ports ------------------------
        .gt6_eyescandataerror_out       (gt6_eyescandataerror_out), // output wire gt6_eyescandataerror_out
        .gt6_eyescantrigger_in          (gt6_eyescantrigger_in), // input wire gt6_eyescantrigger_in
    //---------------- Receive Ports - FPGA RX Interface Ports -----------------
        .gt6_rxusrclk_in                (gt6_rxusrclk_in), // input wire gt6_rxusrclk_in
        .gt6_rxusrclk2_in               (gt6_rxusrclk2_in), // input wire gt6_rxusrclk2_in
    //---------------- Receive Ports - FPGA RX interface Ports -----------------
        .gt6_rxdata_out                 (gt6_rxdata_out), // output wire [31:0] gt6_rxdata_out
    //------------------------- Receive Ports - RX AFE -------------------------
        .gt6_gtxrxp_in                  (gt6_gtxrxp_in), // input wire gt6_gtxrxp_in
    //---------------------- Receive Ports - RX AFE Ports ----------------------
        .gt6_gtxrxn_in                  (gt6_gtxrxn_in), // input wire gt6_gtxrxn_in
    //------------------- Receive Ports - RX Equalizer Ports -------------------
        .gt6_rxdfelpmreset_in           (gt6_rxdfelpmreset_in), // input wire gt6_rxdfelpmreset_in
        .gt6_rxmonitorout_out           (gt6_rxmonitorout_out), // output wire [6:0] gt6_rxmonitorout_out
        .gt6_rxmonitorsel_in            (gt6_rxmonitorsel_in), // input wire [1:0] gt6_rxmonitorsel_in
    //------------- Receive Ports - RX Fabric Output Control Ports -------------
        .gt6_rxoutclk_out               (gt6_rxoutclk_out), // output wire gt6_rxoutclk_out
        .gt6_rxoutclkfabric_out         (gt6_rxoutclkfabric_out), // output wire gt6_rxoutclkfabric_out
    //----------- Receive Ports - RX Initialization and Reset Ports ------------
        .gt6_gtrxreset_in               (gt6_gtrxreset_in), // input wire gt6_gtrxreset_in
        .gt6_rxpmareset_in              (gt6_rxpmareset_in), // input wire gt6_rxpmareset_in
    //------------ Receive Ports -RX Initialization and Reset Ports ------------
        .gt6_rxresetdone_out            (gt6_rxresetdone_out), // output wire gt6_rxresetdone_out
    //------------------- TX Initialization and Reset Ports --------------------
        .gt6_gttxreset_in               (gt6_gttxreset_in), // input wire gt6_gttxreset_in
        .gt6_txuserrdy_in               (gt6_txuserrdy_in), // input wire gt6_txuserrdy_in
    //---------------- Transmit Ports - FPGA TX Interface Ports ----------------
        .gt6_txusrclk_in                (gt6_txusrclk_in), // input wire gt6_txusrclk_in
        .gt6_txusrclk2_in               (gt6_txusrclk2_in), // input wire gt6_txusrclk2_in
    //---------------- Transmit Ports - TX Data Path interface -----------------
        .gt6_txdata_in                  (gt6_txdata_in), // input wire [31:0] gt6_txdata_in
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .gt6_gtxtxn_out                 (gt6_gtxtxn_out), // output wire gt6_gtxtxn_out
        .gt6_gtxtxp_out                 (gt6_gtxtxp_out), // output wire gt6_gtxtxp_out
    //--------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        .gt6_txoutclk_out               (gt6_txoutclk_out), // output wire gt6_txoutclk_out
        .gt6_txoutclkfabric_out         (gt6_txoutclkfabric_out), // output wire gt6_txoutclkfabric_out
        .gt6_txoutclkpcs_out            (gt6_txoutclkpcs_out), // output wire gt6_txoutclkpcs_out
    //----------- Transmit Ports - TX Initialization and Reset Ports -----------
        .gt6_txresetdone_out            (gt6_txresetdone_out), // output wire gt6_txresetdone_out


    //____________________________COMMON PORTS________________________________
     .gt0_qplloutclk_in(gt0_qplloutclk_in),
     .gt0_qplloutrefclk_in(gt0_qplloutrefclk_in),
     .gt1_qplloutclk_in(gt1_qplloutclk_in),
     .gt1_qplloutrefclk_in(gt1_qplloutrefclk_in)
    );

endmodule

