-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.3 (win64) Build 2405991 Thu Dec  6 23:38:27 MST 2018
-- Date        : Sun Nov  8 20:18:34 2020
-- Host        : 13-02625 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top gtwizard_0 -prefix
--               gtwizard_0_ gtwizard_0_stub.vhdl
-- Design      : gtwizard_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7k325tffg900-2
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity gtwizard_0 is
  Port ( 
    sysclk_in : in STD_LOGIC;
    soft_reset_tx_in : in STD_LOGIC;
    soft_reset_rx_in : in STD_LOGIC;
    dont_reset_on_data_error_in : in STD_LOGIC;
    gt0_tx_fsm_reset_done_out : out STD_LOGIC;
    gt0_rx_fsm_reset_done_out : out STD_LOGIC;
    gt0_data_valid_in : in STD_LOGIC;
    gt1_tx_fsm_reset_done_out : out STD_LOGIC;
    gt1_rx_fsm_reset_done_out : out STD_LOGIC;
    gt1_data_valid_in : in STD_LOGIC;
    gt2_tx_fsm_reset_done_out : out STD_LOGIC;
    gt2_rx_fsm_reset_done_out : out STD_LOGIC;
    gt2_data_valid_in : in STD_LOGIC;
    gt3_tx_fsm_reset_done_out : out STD_LOGIC;
    gt3_rx_fsm_reset_done_out : out STD_LOGIC;
    gt3_data_valid_in : in STD_LOGIC;
    gt4_tx_fsm_reset_done_out : out STD_LOGIC;
    gt4_rx_fsm_reset_done_out : out STD_LOGIC;
    gt4_data_valid_in : in STD_LOGIC;
    gt5_tx_fsm_reset_done_out : out STD_LOGIC;
    gt5_rx_fsm_reset_done_out : out STD_LOGIC;
    gt5_data_valid_in : in STD_LOGIC;
    gt6_tx_fsm_reset_done_out : out STD_LOGIC;
    gt6_rx_fsm_reset_done_out : out STD_LOGIC;
    gt6_data_valid_in : in STD_LOGIC;
    gt0_cpllfbclklost_out : out STD_LOGIC;
    gt0_cplllock_out : out STD_LOGIC;
    gt0_cplllockdetclk_in : in STD_LOGIC;
    gt0_cpllreset_in : in STD_LOGIC;
    gt0_gtrefclk0_in : in STD_LOGIC;
    gt0_gtrefclk1_in : in STD_LOGIC;
    gt0_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt0_drpclk_in : in STD_LOGIC;
    gt0_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt0_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt0_drpen_in : in STD_LOGIC;
    gt0_drprdy_out : out STD_LOGIC;
    gt0_drpwe_in : in STD_LOGIC;
    gt0_dmonitorout_out : out STD_LOGIC_VECTOR ( 7 downto 0 );
    gt0_eyescanreset_in : in STD_LOGIC;
    gt0_rxuserrdy_in : in STD_LOGIC;
    gt0_eyescandataerror_out : out STD_LOGIC;
    gt0_eyescantrigger_in : in STD_LOGIC;
    gt0_rxusrclk_in : in STD_LOGIC;
    gt0_rxusrclk2_in : in STD_LOGIC;
    gt0_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt0_gtxrxp_in : in STD_LOGIC;
    gt0_gtxrxn_in : in STD_LOGIC;
    gt0_rxdfelpmreset_in : in STD_LOGIC;
    gt0_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt0_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt0_rxoutclk_out : out STD_LOGIC;
    gt0_rxoutclkfabric_out : out STD_LOGIC;
    gt0_gtrxreset_in : in STD_LOGIC;
    gt0_rxpmareset_in : in STD_LOGIC;
    gt0_rxresetdone_out : out STD_LOGIC;
    gt0_gttxreset_in : in STD_LOGIC;
    gt0_txuserrdy_in : in STD_LOGIC;
    gt0_txusrclk_in : in STD_LOGIC;
    gt0_txusrclk2_in : in STD_LOGIC;
    gt0_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt0_gtxtxn_out : out STD_LOGIC;
    gt0_gtxtxp_out : out STD_LOGIC;
    gt0_txoutclk_out : out STD_LOGIC;
    gt0_txoutclkfabric_out : out STD_LOGIC;
    gt0_txoutclkpcs_out : out STD_LOGIC;
    gt0_txresetdone_out : out STD_LOGIC;
    gt1_cpllfbclklost_out : out STD_LOGIC;
    gt1_cplllock_out : out STD_LOGIC;
    gt1_cplllockdetclk_in : in STD_LOGIC;
    gt1_cpllreset_in : in STD_LOGIC;
    gt1_gtrefclk0_in : in STD_LOGIC;
    gt1_gtrefclk1_in : in STD_LOGIC;
    gt1_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt1_drpclk_in : in STD_LOGIC;
    gt1_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt1_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt1_drpen_in : in STD_LOGIC;
    gt1_drprdy_out : out STD_LOGIC;
    gt1_drpwe_in : in STD_LOGIC;
    gt1_dmonitorout_out : out STD_LOGIC_VECTOR ( 7 downto 0 );
    gt1_eyescanreset_in : in STD_LOGIC;
    gt1_rxuserrdy_in : in STD_LOGIC;
    gt1_eyescandataerror_out : out STD_LOGIC;
    gt1_eyescantrigger_in : in STD_LOGIC;
    gt1_rxusrclk_in : in STD_LOGIC;
    gt1_rxusrclk2_in : in STD_LOGIC;
    gt1_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt1_gtxrxp_in : in STD_LOGIC;
    gt1_gtxrxn_in : in STD_LOGIC;
    gt1_rxdfelpmreset_in : in STD_LOGIC;
    gt1_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt1_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt1_rxoutclk_out : out STD_LOGIC;
    gt1_rxoutclkfabric_out : out STD_LOGIC;
    gt1_gtrxreset_in : in STD_LOGIC;
    gt1_rxpmareset_in : in STD_LOGIC;
    gt1_rxresetdone_out : out STD_LOGIC;
    gt1_gttxreset_in : in STD_LOGIC;
    gt1_txuserrdy_in : in STD_LOGIC;
    gt1_txusrclk_in : in STD_LOGIC;
    gt1_txusrclk2_in : in STD_LOGIC;
    gt1_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt1_gtxtxn_out : out STD_LOGIC;
    gt1_gtxtxp_out : out STD_LOGIC;
    gt1_txoutclk_out : out STD_LOGIC;
    gt1_txoutclkfabric_out : out STD_LOGIC;
    gt1_txoutclkpcs_out : out STD_LOGIC;
    gt1_txresetdone_out : out STD_LOGIC;
    gt2_cpllfbclklost_out : out STD_LOGIC;
    gt2_cplllock_out : out STD_LOGIC;
    gt2_cplllockdetclk_in : in STD_LOGIC;
    gt2_cpllreset_in : in STD_LOGIC;
    gt2_gtrefclk0_in : in STD_LOGIC;
    gt2_gtrefclk1_in : in STD_LOGIC;
    gt2_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt2_drpclk_in : in STD_LOGIC;
    gt2_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt2_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt2_drpen_in : in STD_LOGIC;
    gt2_drprdy_out : out STD_LOGIC;
    gt2_drpwe_in : in STD_LOGIC;
    gt2_dmonitorout_out : out STD_LOGIC_VECTOR ( 7 downto 0 );
    gt2_eyescanreset_in : in STD_LOGIC;
    gt2_rxuserrdy_in : in STD_LOGIC;
    gt2_eyescandataerror_out : out STD_LOGIC;
    gt2_eyescantrigger_in : in STD_LOGIC;
    gt2_rxusrclk_in : in STD_LOGIC;
    gt2_rxusrclk2_in : in STD_LOGIC;
    gt2_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt2_gtxrxp_in : in STD_LOGIC;
    gt2_gtxrxn_in : in STD_LOGIC;
    gt2_rxdfelpmreset_in : in STD_LOGIC;
    gt2_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt2_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt2_rxoutclk_out : out STD_LOGIC;
    gt2_rxoutclkfabric_out : out STD_LOGIC;
    gt2_gtrxreset_in : in STD_LOGIC;
    gt2_rxpmareset_in : in STD_LOGIC;
    gt2_rxresetdone_out : out STD_LOGIC;
    gt2_gttxreset_in : in STD_LOGIC;
    gt2_txuserrdy_in : in STD_LOGIC;
    gt2_txusrclk_in : in STD_LOGIC;
    gt2_txusrclk2_in : in STD_LOGIC;
    gt2_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt2_gtxtxn_out : out STD_LOGIC;
    gt2_gtxtxp_out : out STD_LOGIC;
    gt2_txoutclk_out : out STD_LOGIC;
    gt2_txoutclkfabric_out : out STD_LOGIC;
    gt2_txoutclkpcs_out : out STD_LOGIC;
    gt2_txresetdone_out : out STD_LOGIC;
    gt3_cpllfbclklost_out : out STD_LOGIC;
    gt3_cplllock_out : out STD_LOGIC;
    gt3_cplllockdetclk_in : in STD_LOGIC;
    gt3_cpllreset_in : in STD_LOGIC;
    gt3_gtrefclk0_in : in STD_LOGIC;
    gt3_gtrefclk1_in : in STD_LOGIC;
    gt3_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt3_drpclk_in : in STD_LOGIC;
    gt3_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt3_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt3_drpen_in : in STD_LOGIC;
    gt3_drprdy_out : out STD_LOGIC;
    gt3_drpwe_in : in STD_LOGIC;
    gt3_dmonitorout_out : out STD_LOGIC_VECTOR ( 7 downto 0 );
    gt3_eyescanreset_in : in STD_LOGIC;
    gt3_rxuserrdy_in : in STD_LOGIC;
    gt3_eyescandataerror_out : out STD_LOGIC;
    gt3_eyescantrigger_in : in STD_LOGIC;
    gt3_rxusrclk_in : in STD_LOGIC;
    gt3_rxusrclk2_in : in STD_LOGIC;
    gt3_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt3_gtxrxp_in : in STD_LOGIC;
    gt3_gtxrxn_in : in STD_LOGIC;
    gt3_rxdfelpmreset_in : in STD_LOGIC;
    gt3_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt3_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt3_rxoutclk_out : out STD_LOGIC;
    gt3_rxoutclkfabric_out : out STD_LOGIC;
    gt3_gtrxreset_in : in STD_LOGIC;
    gt3_rxpmareset_in : in STD_LOGIC;
    gt3_rxresetdone_out : out STD_LOGIC;
    gt3_gttxreset_in : in STD_LOGIC;
    gt3_txuserrdy_in : in STD_LOGIC;
    gt3_txusrclk_in : in STD_LOGIC;
    gt3_txusrclk2_in : in STD_LOGIC;
    gt3_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt3_gtxtxn_out : out STD_LOGIC;
    gt3_gtxtxp_out : out STD_LOGIC;
    gt3_txoutclk_out : out STD_LOGIC;
    gt3_txoutclkfabric_out : out STD_LOGIC;
    gt3_txoutclkpcs_out : out STD_LOGIC;
    gt3_txresetdone_out : out STD_LOGIC;
    gt4_cpllfbclklost_out : out STD_LOGIC;
    gt4_cplllock_out : out STD_LOGIC;
    gt4_cplllockdetclk_in : in STD_LOGIC;
    gt4_cpllreset_in : in STD_LOGIC;
    gt4_gtrefclk0_in : in STD_LOGIC;
    gt4_gtrefclk1_in : in STD_LOGIC;
    gt4_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt4_drpclk_in : in STD_LOGIC;
    gt4_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt4_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt4_drpen_in : in STD_LOGIC;
    gt4_drprdy_out : out STD_LOGIC;
    gt4_drpwe_in : in STD_LOGIC;
    gt4_dmonitorout_out : out STD_LOGIC_VECTOR ( 7 downto 0 );
    gt4_eyescanreset_in : in STD_LOGIC;
    gt4_rxuserrdy_in : in STD_LOGIC;
    gt4_eyescandataerror_out : out STD_LOGIC;
    gt4_eyescantrigger_in : in STD_LOGIC;
    gt4_rxusrclk_in : in STD_LOGIC;
    gt4_rxusrclk2_in : in STD_LOGIC;
    gt4_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt4_gtxrxp_in : in STD_LOGIC;
    gt4_gtxrxn_in : in STD_LOGIC;
    gt4_rxdfelpmreset_in : in STD_LOGIC;
    gt4_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt4_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt4_rxoutclk_out : out STD_LOGIC;
    gt4_rxoutclkfabric_out : out STD_LOGIC;
    gt4_gtrxreset_in : in STD_LOGIC;
    gt4_rxpmareset_in : in STD_LOGIC;
    gt4_rxresetdone_out : out STD_LOGIC;
    gt4_gttxreset_in : in STD_LOGIC;
    gt4_txuserrdy_in : in STD_LOGIC;
    gt4_txusrclk_in : in STD_LOGIC;
    gt4_txusrclk2_in : in STD_LOGIC;
    gt4_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt4_gtxtxn_out : out STD_LOGIC;
    gt4_gtxtxp_out : out STD_LOGIC;
    gt4_txoutclk_out : out STD_LOGIC;
    gt4_txoutclkfabric_out : out STD_LOGIC;
    gt4_txoutclkpcs_out : out STD_LOGIC;
    gt4_txresetdone_out : out STD_LOGIC;
    gt5_cpllfbclklost_out : out STD_LOGIC;
    gt5_cplllock_out : out STD_LOGIC;
    gt5_cplllockdetclk_in : in STD_LOGIC;
    gt5_cpllreset_in : in STD_LOGIC;
    gt5_gtrefclk0_in : in STD_LOGIC;
    gt5_gtrefclk1_in : in STD_LOGIC;
    gt5_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt5_drpclk_in : in STD_LOGIC;
    gt5_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt5_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt5_drpen_in : in STD_LOGIC;
    gt5_drprdy_out : out STD_LOGIC;
    gt5_drpwe_in : in STD_LOGIC;
    gt5_dmonitorout_out : out STD_LOGIC_VECTOR ( 7 downto 0 );
    gt5_eyescanreset_in : in STD_LOGIC;
    gt5_rxuserrdy_in : in STD_LOGIC;
    gt5_eyescandataerror_out : out STD_LOGIC;
    gt5_eyescantrigger_in : in STD_LOGIC;
    gt5_rxusrclk_in : in STD_LOGIC;
    gt5_rxusrclk2_in : in STD_LOGIC;
    gt5_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt5_gtxrxp_in : in STD_LOGIC;
    gt5_gtxrxn_in : in STD_LOGIC;
    gt5_rxdfelpmreset_in : in STD_LOGIC;
    gt5_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt5_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt5_rxoutclk_out : out STD_LOGIC;
    gt5_rxoutclkfabric_out : out STD_LOGIC;
    gt5_gtrxreset_in : in STD_LOGIC;
    gt5_rxpmareset_in : in STD_LOGIC;
    gt5_rxresetdone_out : out STD_LOGIC;
    gt5_gttxreset_in : in STD_LOGIC;
    gt5_txuserrdy_in : in STD_LOGIC;
    gt5_txusrclk_in : in STD_LOGIC;
    gt5_txusrclk2_in : in STD_LOGIC;
    gt5_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt5_gtxtxn_out : out STD_LOGIC;
    gt5_gtxtxp_out : out STD_LOGIC;
    gt5_txoutclk_out : out STD_LOGIC;
    gt5_txoutclkfabric_out : out STD_LOGIC;
    gt5_txoutclkpcs_out : out STD_LOGIC;
    gt5_txresetdone_out : out STD_LOGIC;
    gt6_cpllfbclklost_out : out STD_LOGIC;
    gt6_cplllock_out : out STD_LOGIC;
    gt6_cplllockdetclk_in : in STD_LOGIC;
    gt6_cpllreset_in : in STD_LOGIC;
    gt6_gtrefclk0_in : in STD_LOGIC;
    gt6_gtrefclk1_in : in STD_LOGIC;
    gt6_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt6_drpclk_in : in STD_LOGIC;
    gt6_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt6_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt6_drpen_in : in STD_LOGIC;
    gt6_drprdy_out : out STD_LOGIC;
    gt6_drpwe_in : in STD_LOGIC;
    gt6_dmonitorout_out : out STD_LOGIC_VECTOR ( 7 downto 0 );
    gt6_eyescanreset_in : in STD_LOGIC;
    gt6_rxuserrdy_in : in STD_LOGIC;
    gt6_eyescandataerror_out : out STD_LOGIC;
    gt6_eyescantrigger_in : in STD_LOGIC;
    gt6_rxusrclk_in : in STD_LOGIC;
    gt6_rxusrclk2_in : in STD_LOGIC;
    gt6_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt6_gtxrxp_in : in STD_LOGIC;
    gt6_gtxrxn_in : in STD_LOGIC;
    gt6_rxdfelpmreset_in : in STD_LOGIC;
    gt6_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt6_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt6_rxoutclk_out : out STD_LOGIC;
    gt6_rxoutclkfabric_out : out STD_LOGIC;
    gt6_gtrxreset_in : in STD_LOGIC;
    gt6_rxpmareset_in : in STD_LOGIC;
    gt6_rxresetdone_out : out STD_LOGIC;
    gt6_gttxreset_in : in STD_LOGIC;
    gt6_txuserrdy_in : in STD_LOGIC;
    gt6_txusrclk_in : in STD_LOGIC;
    gt6_txusrclk2_in : in STD_LOGIC;
    gt6_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt6_gtxtxn_out : out STD_LOGIC;
    gt6_gtxtxp_out : out STD_LOGIC;
    gt6_txoutclk_out : out STD_LOGIC;
    gt6_txoutclkfabric_out : out STD_LOGIC;
    gt6_txoutclkpcs_out : out STD_LOGIC;
    gt6_txresetdone_out : out STD_LOGIC;
    gt0_qplloutclk_in : in STD_LOGIC;
    gt0_qplloutrefclk_in : in STD_LOGIC;
    gt1_qplloutclk_in : in STD_LOGIC;
    gt1_qplloutrefclk_in : in STD_LOGIC
  );

end gtwizard_0;

architecture stub of gtwizard_0 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "sysclk_in,soft_reset_tx_in,soft_reset_rx_in,dont_reset_on_data_error_in,gt0_tx_fsm_reset_done_out,gt0_rx_fsm_reset_done_out,gt0_data_valid_in,gt1_tx_fsm_reset_done_out,gt1_rx_fsm_reset_done_out,gt1_data_valid_in,gt2_tx_fsm_reset_done_out,gt2_rx_fsm_reset_done_out,gt2_data_valid_in,gt3_tx_fsm_reset_done_out,gt3_rx_fsm_reset_done_out,gt3_data_valid_in,gt4_tx_fsm_reset_done_out,gt4_rx_fsm_reset_done_out,gt4_data_valid_in,gt5_tx_fsm_reset_done_out,gt5_rx_fsm_reset_done_out,gt5_data_valid_in,gt6_tx_fsm_reset_done_out,gt6_rx_fsm_reset_done_out,gt6_data_valid_in,gt0_cpllfbclklost_out,gt0_cplllock_out,gt0_cplllockdetclk_in,gt0_cpllreset_in,gt0_gtrefclk0_in,gt0_gtrefclk1_in,gt0_drpaddr_in[8:0],gt0_drpclk_in,gt0_drpdi_in[15:0],gt0_drpdo_out[15:0],gt0_drpen_in,gt0_drprdy_out,gt0_drpwe_in,gt0_dmonitorout_out[7:0],gt0_eyescanreset_in,gt0_rxuserrdy_in,gt0_eyescandataerror_out,gt0_eyescantrigger_in,gt0_rxusrclk_in,gt0_rxusrclk2_in,gt0_rxdata_out[31:0],gt0_gtxrxp_in,gt0_gtxrxn_in,gt0_rxdfelpmreset_in,gt0_rxmonitorout_out[6:0],gt0_rxmonitorsel_in[1:0],gt0_rxoutclk_out,gt0_rxoutclkfabric_out,gt0_gtrxreset_in,gt0_rxpmareset_in,gt0_rxresetdone_out,gt0_gttxreset_in,gt0_txuserrdy_in,gt0_txusrclk_in,gt0_txusrclk2_in,gt0_txdata_in[31:0],gt0_gtxtxn_out,gt0_gtxtxp_out,gt0_txoutclk_out,gt0_txoutclkfabric_out,gt0_txoutclkpcs_out,gt0_txresetdone_out,gt1_cpllfbclklost_out,gt1_cplllock_out,gt1_cplllockdetclk_in,gt1_cpllreset_in,gt1_gtrefclk0_in,gt1_gtrefclk1_in,gt1_drpaddr_in[8:0],gt1_drpclk_in,gt1_drpdi_in[15:0],gt1_drpdo_out[15:0],gt1_drpen_in,gt1_drprdy_out,gt1_drpwe_in,gt1_dmonitorout_out[7:0],gt1_eyescanreset_in,gt1_rxuserrdy_in,gt1_eyescandataerror_out,gt1_eyescantrigger_in,gt1_rxusrclk_in,gt1_rxusrclk2_in,gt1_rxdata_out[31:0],gt1_gtxrxp_in,gt1_gtxrxn_in,gt1_rxdfelpmreset_in,gt1_rxmonitorout_out[6:0],gt1_rxmonitorsel_in[1:0],gt1_rxoutclk_out,gt1_rxoutclkfabric_out,gt1_gtrxreset_in,gt1_rxpmareset_in,gt1_rxresetdone_out,gt1_gttxreset_in,gt1_txuserrdy_in,gt1_txusrclk_in,gt1_txusrclk2_in,gt1_txdata_in[31:0],gt1_gtxtxn_out,gt1_gtxtxp_out,gt1_txoutclk_out,gt1_txoutclkfabric_out,gt1_txoutclkpcs_out,gt1_txresetdone_out,gt2_cpllfbclklost_out,gt2_cplllock_out,gt2_cplllockdetclk_in,gt2_cpllreset_in,gt2_gtrefclk0_in,gt2_gtrefclk1_in,gt2_drpaddr_in[8:0],gt2_drpclk_in,gt2_drpdi_in[15:0],gt2_drpdo_out[15:0],gt2_drpen_in,gt2_drprdy_out,gt2_drpwe_in,gt2_dmonitorout_out[7:0],gt2_eyescanreset_in,gt2_rxuserrdy_in,gt2_eyescandataerror_out,gt2_eyescantrigger_in,gt2_rxusrclk_in,gt2_rxusrclk2_in,gt2_rxdata_out[31:0],gt2_gtxrxp_in,gt2_gtxrxn_in,gt2_rxdfelpmreset_in,gt2_rxmonitorout_out[6:0],gt2_rxmonitorsel_in[1:0],gt2_rxoutclk_out,gt2_rxoutclkfabric_out,gt2_gtrxreset_in,gt2_rxpmareset_in,gt2_rxresetdone_out,gt2_gttxreset_in,gt2_txuserrdy_in,gt2_txusrclk_in,gt2_txusrclk2_in,gt2_txdata_in[31:0],gt2_gtxtxn_out,gt2_gtxtxp_out,gt2_txoutclk_out,gt2_txoutclkfabric_out,gt2_txoutclkpcs_out,gt2_txresetdone_out,gt3_cpllfbclklost_out,gt3_cplllock_out,gt3_cplllockdetclk_in,gt3_cpllreset_in,gt3_gtrefclk0_in,gt3_gtrefclk1_in,gt3_drpaddr_in[8:0],gt3_drpclk_in,gt3_drpdi_in[15:0],gt3_drpdo_out[15:0],gt3_drpen_in,gt3_drprdy_out,gt3_drpwe_in,gt3_dmonitorout_out[7:0],gt3_eyescanreset_in,gt3_rxuserrdy_in,gt3_eyescandataerror_out,gt3_eyescantrigger_in,gt3_rxusrclk_in,gt3_rxusrclk2_in,gt3_rxdata_out[31:0],gt3_gtxrxp_in,gt3_gtxrxn_in,gt3_rxdfelpmreset_in,gt3_rxmonitorout_out[6:0],gt3_rxmonitorsel_in[1:0],gt3_rxoutclk_out,gt3_rxoutclkfabric_out,gt3_gtrxreset_in,gt3_rxpmareset_in,gt3_rxresetdone_out,gt3_gttxreset_in,gt3_txuserrdy_in,gt3_txusrclk_in,gt3_txusrclk2_in,gt3_txdata_in[31:0],gt3_gtxtxn_out,gt3_gtxtxp_out,gt3_txoutclk_out,gt3_txoutclkfabric_out,gt3_txoutclkpcs_out,gt3_txresetdone_out,gt4_cpllfbclklost_out,gt4_cplllock_out,gt4_cplllockdetclk_in,gt4_cpllreset_in,gt4_gtrefclk0_in,gt4_gtrefclk1_in,gt4_drpaddr_in[8:0],gt4_drpclk_in,gt4_drpdi_in[15:0],gt4_drpdo_out[15:0],gt4_drpen_in,gt4_drprdy_out,gt4_drpwe_in,gt4_dmonitorout_out[7:0],gt4_eyescanreset_in,gt4_rxuserrdy_in,gt4_eyescandataerror_out,gt4_eyescantrigger_in,gt4_rxusrclk_in,gt4_rxusrclk2_in,gt4_rxdata_out[31:0],gt4_gtxrxp_in,gt4_gtxrxn_in,gt4_rxdfelpmreset_in,gt4_rxmonitorout_out[6:0],gt4_rxmonitorsel_in[1:0],gt4_rxoutclk_out,gt4_rxoutclkfabric_out,gt4_gtrxreset_in,gt4_rxpmareset_in,gt4_rxresetdone_out,gt4_gttxreset_in,gt4_txuserrdy_in,gt4_txusrclk_in,gt4_txusrclk2_in,gt4_txdata_in[31:0],gt4_gtxtxn_out,gt4_gtxtxp_out,gt4_txoutclk_out,gt4_txoutclkfabric_out,gt4_txoutclkpcs_out,gt4_txresetdone_out,gt5_cpllfbclklost_out,gt5_cplllock_out,gt5_cplllockdetclk_in,gt5_cpllreset_in,gt5_gtrefclk0_in,gt5_gtrefclk1_in,gt5_drpaddr_in[8:0],gt5_drpclk_in,gt5_drpdi_in[15:0],gt5_drpdo_out[15:0],gt5_drpen_in,gt5_drprdy_out,gt5_drpwe_in,gt5_dmonitorout_out[7:0],gt5_eyescanreset_in,gt5_rxuserrdy_in,gt5_eyescandataerror_out,gt5_eyescantrigger_in,gt5_rxusrclk_in,gt5_rxusrclk2_in,gt5_rxdata_out[31:0],gt5_gtxrxp_in,gt5_gtxrxn_in,gt5_rxdfelpmreset_in,gt5_rxmonitorout_out[6:0],gt5_rxmonitorsel_in[1:0],gt5_rxoutclk_out,gt5_rxoutclkfabric_out,gt5_gtrxreset_in,gt5_rxpmareset_in,gt5_rxresetdone_out,gt5_gttxreset_in,gt5_txuserrdy_in,gt5_txusrclk_in,gt5_txusrclk2_in,gt5_txdata_in[31:0],gt5_gtxtxn_out,gt5_gtxtxp_out,gt5_txoutclk_out,gt5_txoutclkfabric_out,gt5_txoutclkpcs_out,gt5_txresetdone_out,gt6_cpllfbclklost_out,gt6_cplllock_out,gt6_cplllockdetclk_in,gt6_cpllreset_in,gt6_gtrefclk0_in,gt6_gtrefclk1_in,gt6_drpaddr_in[8:0],gt6_drpclk_in,gt6_drpdi_in[15:0],gt6_drpdo_out[15:0],gt6_drpen_in,gt6_drprdy_out,gt6_drpwe_in,gt6_dmonitorout_out[7:0],gt6_eyescanreset_in,gt6_rxuserrdy_in,gt6_eyescandataerror_out,gt6_eyescantrigger_in,gt6_rxusrclk_in,gt6_rxusrclk2_in,gt6_rxdata_out[31:0],gt6_gtxrxp_in,gt6_gtxrxn_in,gt6_rxdfelpmreset_in,gt6_rxmonitorout_out[6:0],gt6_rxmonitorsel_in[1:0],gt6_rxoutclk_out,gt6_rxoutclkfabric_out,gt6_gtrxreset_in,gt6_rxpmareset_in,gt6_rxresetdone_out,gt6_gttxreset_in,gt6_txuserrdy_in,gt6_txusrclk_in,gt6_txusrclk2_in,gt6_txdata_in[31:0],gt6_gtxtxn_out,gt6_gtxtxp_out,gt6_txoutclk_out,gt6_txoutclkfabric_out,gt6_txoutclkpcs_out,gt6_txresetdone_out,gt0_qplloutclk_in,gt0_qplloutrefclk_in,gt1_qplloutclk_in,gt1_qplloutrefclk_in";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "gtwizard_0,gtwizard_v3_6_10,{protocol_file=Start_from_scratch}";
begin
end;
